import convert
import os
import matplotlib.pyplot as plt
import numpy as np
import bezier

'''
For now, plots the data generated by convert.py
Later will generate bezier curves from it
'''
script_dir = os.path.dirname(__file__)
#rel_path = "../data/load/thrustcurve/AeroTech_D10.eng"
#rel_path = "../data/load/thrustcurve/AeroTech_D21.rse"
#rel_path = "../data/load/thrustcurve/AeroTech_H45.edx"
rel_path = "../data/load/thrustcurve/AeroTech_H45.txt"
abs_path = os.path.join(script_dir, rel_path) #connects the path of where the file is being run, __file__, with the relative path of the data'''
file = open(abs_path)

#data = convert.converteng(file) #test
#data = convert.convertrse(file) #test
#data = convert.convertedx(file) #test
data = convert.convertcompuroc(file) #test This is the only one that doesn't work

xs = []
ys = []
for pair in data:
    #print(pair)
    xs.append(pair[0])

for pair in data:
    ys.append(pair[1])

nodes = np.asfortranarray([xs,ys])
#nodes = np.asfortranarray([[0.0, 0.625, 1.0],[0.0, 0.5, 0.5]])
#print(nodes)
curve1 = bezier.Curve(nodes, degree=3)
curve1.plot(num_pts=256)
plt.show()


plt.plot(xs, ys)
plt.show()
